### ISSUE TITLE
Zenhub Review

### ISSUE THREAD

**Issue by reissmatt** [reissmatt/risen-one-mission-platform#1]
## Notes
This issue is to address sharing things about Zenhub and all its functionality. 

## Acceptance Criteria
- [ ] Product Owner is established
- [ ] Program Owner is established
- [ ] Design is up to speed
- [ ] Dev is up to speed

## Tasks
- [x] Initiate a meeting to walk through Zenhub
- [x] Walk through creating an account
- [x] Add team members to repo and Zenhub board

## Definition of Done
- [ ] Risen One team is in the new repo
- [ ] Risen One team is in the new Zenhub board
